### ISSUE TITLE
Unable to start with docker-compose

### ISSUE THREAD

**Issue by stachdude** [blacktop/docker-kafka-alpine#1]
Zookeeper starts but kafka node does not.

```
sed: unsupported command /
```

This is the only log entry that I can find.

**Comment by blacktop** [comment]
@stachdude did you change the docker-compose.yml at all?  I just tried on my mac and it is working using Docker for Mac.  

However, I think I remember seeing that error when I tried it at work.  

My kafka image isn't were I want it to be and there will be a lot more changes before I consider it prod.  For example the ability to scale up kafka brokers with docker-compose etc.

**Comment by stachdude** [comment]
@blacktop No I didn't change the yml file. This is the behavior of the clean pull of this git project. And I'm running it on linux but that shouldn't be of any difference, considering the docker ideology.

**Comment by blacktop** [comment]
it seems to be working now.  can you please confirm?
