### ISSUE TITLE
zookeeper is not a recognized option

### ISSUE THREAD

**Issue by rssarto** [blacktop/docker-kafka-alpine#10]
Hi Team!
I tried to use the backtop's latest version, but I got the following error when I tried to start the container:

`Exception in thread "main" joptsimple.UnrecognizedOptionException: zookeeper is not a recognized option`

I think the problem is related to the --zookeeper used in the command below:

https://github.com/blacktop/docker-kafka-alpine/blob/3c7032c465d0feacaf9641383f5418d4db2f87a3/3.1/scripts/create-topics.sh#L37

Newer versions(2.2+) of Kafka no longer requires ZooKeeper connection string.

**Comment by blacktop** [comment]
let me know if that last commit helped

**Comment by rssarto** [comment]
Thank you, it worked like a charm.
