### ISSUE TITLE
Publish arm64 image for M1 and M2

### ISSUE THREAD

**Issue by pmorelli92** [blacktop/docker-kafka-alpine#11]
Can you please publish this image type for people using ARM architecture to work?
https://docs.docker.com/build/building/multi-platform/

Something like the following should work:

```
docker buildx build --push -t "blacktop/docker-kafka-alpine" --platform linux/amd64,linux/arm64 .
```

**Comment by blacktop** [comment]
added to CI/CD

**Comment by pmorelli92** [comment]
Thanks a lot!!!
