### ISSUE TITLE
Auto creation of topics is switched off

### ISSUE THREAD

**Issue by kelveden** [blacktop/docker-kafka-alpine#3]
Just recently I've been seeing a lot of this sort of error start to happen in my tests that make use of `blacktop/kafka:0.10`:

```
Error while fetching metadata with correlation id 0 : {producer-topic=UNKNOWN_TOPIC_OR_PARTITION}
```

The problem seems to be as a result of this recent change: https://github.com/blacktop/docker-kafka-alpine/commit/503467301d35b11369812823554824b19314c3e2#diff-ce7d1556313e0097067704a2ac200740R118. i.e. kafka will not auto-create topics whereas before it did. The [Apache docs](https://kafka.apache.org/documentation/#brokerconfigs) give the setting as being switched on by default.

So, is the change deliberate?

A workaround is to just switch it back on by specifying the following environment variable: `KAFKA_AUTO_CREATE_TOPICS_ENABLE=true`

**Comment by blacktop** [comment]
I apologize for that.  

I made a few changes trying to move towards a newer way of automating this and left if in a unfinished state.  I didn't know anyone other than me was using this docker image 😉

Thank you for letting me know about this bug. 👍

**Comment by kelveden** [comment]
No problem. Thanks for taking a look so quickly.

Yeah we're making use of the image for automated testing - it has proved useful for wrapping the whole kafka + zookeeper orchestration into one place.
