### ISSUE TITLE
blacktop/kafka:1.1: not present

### ISSUE THREAD

**Issue by mbana** [blacktop/docker-kafka-alpine#6]
```sh
docker pull blacktop/kafka:1.1
Error response from daemon: manifest for blacktop/kafka:1.1 not found
```

Can you please publish `1.1`.

**Comment by blacktop** [comment]
Sorry about that, I always forget to go to docker cloud and MANUALLY tell it to start building a new tag out of a new folder.  I started the build and it should be ready soon.
